name: 'CI build'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: app/MyHTTPFunction/package-lock.json

    - run: npm ci
      working-directory: ./app/MyHTTPFunction

    - run: npm test
      working-directory: ./app/MyHTTPFunction

    - run: npm run compile:ci
      working-directory: ./app/MyHTTPFunction


    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: `google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'app/MyHTTPFunction/dist/my-http-function.zip'
        destination: 'gs://artifact-sandbox-381502/MyHTTPFunction/myfunction-${{ github.sha }}.zip'

